export default{
    UPDATE_FECHA: "UPDATE_FECHA",
    GET_ESTRENO:"GET_ESTRENO",
    GET_ESTRENO_PENDING:"GET_ESTRENO_PENDING",
    GET_ESTRENO_FULFILLED:"GET_ESTRENO_FULFILLED",
    GET_ESTRENO_REJECTED:"GET_ESTRENO_REJECTED",

    //acciones de proximos estrenos
    GET_PROXIMO_ESTRENO: "GET_PROXIMO_ESTRENO",
    GET_PROXIMO_ESTRENO_PENDING:"GET_PROXIMO_ESTRENO_PENDING",
    GET_PROXIMO_ESTRENO_FULFILLED: "GET_PROXIMO_ESTRENO_FULFILLED",
    GET_PROXIMO_ESTRENO_REJECTED:"GET_PROXIMO_ESTRENO_REJECTED",

    //acciones de detalles pelicula
    GET_DETALLE_PELICULA: "GET_DETALLE_PELICULA",
    GET_DETALLE_PELICULA_PENDING: "GET_DETALLE_PELICULA_PENDING",
    GET_DETALLE_PELICULA_FULFILLED: "GET_DETALLE_PELICULA_FULFILLED",
    GET_DETALLE_PELICULA_REJECTED: "GET_DETALLE_PELICULA_REJECTED",
    
    //acciones de creditos peliculas
    GET_CREDITO_PELICULA: "GET_CREDITO_PELICULA",
    GET_CREDITO_PELICULA_PENDING: "GET_CREDITO_PELICULA_PENDING",
    GET_CREDITO_PELICULA_FULFILLED: "GET_CREDITO_PELICULA_FULFILLED",
    GET_CREDITO_PELICULA_REJECTED: "GET_CREDITO_PELICULA_REJECTED",

    //acciones de busqueda de peliculas
    GET_SEARCH:"GET_SEARCH",
    GET_SEARCH_PENDING:"GET_SEARCH_PENDING",
    GET_SEARCH_FULFILLED:"GET_SEARCH_FULFILLED",
    GET_SEARCH_REJECTED:"GET_SEARCH_REJECTED",

    //accion de eliminar
    GET_RESET_DATA:"GET_RESET_DATA",

    //accion de agregar trailer
    GET_TRAILER_MOVIE:"GET_TRAILER_MOVIE",
    GET_TRAILER_MOVIE_PENDING:"GET_TRAILER_MOVIE_PENDING",
    GET_TRAILER_MOVIE_FULFILLED:"GET_TRAILER_MOVIE_FULFILLED",
    GET_TRAILER_MOVIE_REJECTED:"GET_TRAILER_MOVIE_REJECTED",

}